name: Build & Release APK
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./src
      
      - name: Move to workspace root
        run: |
          ls -la ./src
          cd ./src
          ls -la
          pwd
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './src/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./src
        run: npm ci --force
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Build APK
        working-directory: ./src
        run: eas build --platform android --non-interactive
